### PR TITLE
Allow dynamic resizing

### PR DESCRIPTION
**Pull request by mrubli**

### CODE REVIEW

**Comment by TheGreatRefrigerator** [comment]
Hi @mrubli,
i didn't start working on this yet.
So any working solution is welcome :)

I changed the base to development.
will have a look at this later.
cheers

**Comment by TheGreatRefrigerator** [comment]
Hi @mrubli,

I tested your changes and as always have things to complain about 😬.
You seem to be much more comfortable with d3 than myself so maybe you can give me your thoughts
(if it's feasible or can be easily done):
- adjust legend labels with resizing
grafik
- set reasonable minimum value for width/height
grafik

**Comment by mrubli** [comment]
> I tested your changes and as always have things to complain about 😬.

That's what PRs are for. 😉

> You seem to be much more comfortable with d3 than myself so maybe you can give me your thoughts
> (if it's feasible or can be easily done):

I wouldn't call it comfortable, I really just read the API doc and try stuff ... 😄 The issues you mentioned also caught my eye while testing:

> * adjust legend labels with resizing
>   grafik

This was going to be the next item I wanted to attack. It has little to do with dynamic resizing itself and you can reproduce it simply by specifying too small a size when creating the height graph. Let me think about how this is best fixed. I might make it a separate PR though, if that's okay with you.

> * set reasonable minimum value for width/height
>   grafik

This one is also not unique to dynamic resizing. Luckily this is really easily addressed on the client side where the resizing is implemented to begin with. So with JQuery UI you'd just add the `minWidth` and `minHeight` attributes:

```
$('.heightgraph').resizable({
	handles: 'w, s, sw',
	minWidth: 180,
	minHeight: 90,
	resize: function(event, ui) { … }
	stop: function(event, ui) { … }
});
```

I can add that to the sample, though I was wondering whether you have a better suggestion for organizing multiple samples than the simple file duplication I used.

**Comment by TheGreatRefrigerator** [comment]
>  It has little to do with dynamic resizing itself

> also not unique to dynamic resizing

I agree to both. 

A heightgraph with width and height = 10 px doesn't make much sense though.
So we might want to have an internal minimum limit to both width and height instead of having to specify the minimum limit from outside the plugin.
But that's also something for another PR then.

I'm not sure yet what's the best way for having different examples.
In general if it doesn't break other stuff or doesn't introduce huge additional dependencies, i would put it in the main example.

I will use the resize function in [this vue2-leaflet plugin](https://github.com/GIScience/vue2-leaflet-height-graph) to make it easily resizable.
thanks a lot for this 👍

**Comment by TheGreatRefrigerator** [comment]
https://github.com/GIScience/Leaflet.Heightgraph/commit/3174eb125b9f623f06b725f416bc0b5307754f70
Integrated

**Comment by mrubli** [comment]
Thanks for merging!

I've created another small PR to show how clients can address the "reasonable minimum size" problem: https://github.com/GIScience/Leaflet.Heightgraph/pull/86

And I've created https://github.com/GIScience/Leaflet.Heightgraph/issues/87 to track the overlapping axis labels.

**Pull request closed without merging**
