### PR TITLE
Use browserify/require for d3 dependency

### PR DESCRIPTION
**Pull request by mrubli**
This PR addresses https://github.com/GIScience/Leaflet.Heightgraph/issues/45 and makes it much easier for other projects to depend on Leaflet.Heightgraph without having to explicitly include transitive dependencies (d3 in this case).

### CODE REVIEW

**Comment by boldtrn** [comment]
Thanks for this PR, the changes look alright to me. @TheGreatRefrigerator could you have a look at this PR? Are the changes OK for you?

**Comment by TheGreatRefrigerator** [comment]
Hi @mrubli @boldtrn,

i was actually working on this in november last year it seems but somehow stopped ...
Had to switch to something else that had "higher priority"

Could you please check the rollup branch?( just use the dependency as below)
It should bundle all needed d3 functions and require only this dependency in your package.json
```
  "dependencies": {
    "leaflet.heightgraph": "git+https://github.com/GIScience/Leaflet.Heightgraph#rollup"
  },
```
I have to check again, if there is nothing else broken with this.

Would this be sufficient for you?

I didn't have a closer look on this PR yet.
If i should check something else please notify me.

**Comment by boldtrn** [comment]
Thanks for the update @TheGreatRefrigerator. Shouldn't we merge either one of these changes to the master?

**Comment by TheGreatRefrigerator** [comment]
> Shouldn't we merge either one of these changes to the master?

The rollup bundle is about 50% the size of the browserify bundle (due to tree shaking) so we will definitely use rollup.
Changing to rollup will break the coverage and overhaul all of the build and test workflows as grunt will be removed.
So this is a pretty big change.

I wanted to make the coverage work before i merge, but it isn't that significant atm, so i might as well leave it broken for now.

Should be done by the end of the day.

Closing this in favor of rollup

**Comment by mrubli** [comment]
@TheGreatRefrigerator Sorry, I was offline for a couple of days.

> Would this be sufficient for you?

Yes, this works great. I've just tested against the latest version and everything looks good. Thanks! 👍

**Pull request closed without merging**
