### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by boldtrn**
This PR prepares to release v0.1.0 to npm including the latest improvements.

### CODE REVIEW

**Comment by boldtrn** [comment]
I just published 0.1.0

**Comment by TimMcCauley** [comment]
Perfect - thanks a bunch @boldtrn

**Comment by karussell** [comment]
Thanks @boldtrn !

I just updated it and now the background color was removed:

image

Do I need to change something in the styles?

**Comment by boldtrn** [comment]
Thanks for the report @karussell. I haven't change anything about the styles. Is it happening in different browsers or only in a particular browser?

**Comment by karussell** [comment]
Ah, seems to be a firefox issue. The map layer is somehow printed above the background (could see this when internet was slow). But changing the z-index for .leaflet-control does not seem to help.

**Comment by boldtrn** [comment]
@karussell I just checked the demo application with Firefox and could not reproduce the issue. Should I have a look at GH maps?

**Comment by karussell** [comment]
This would be nice, yes :)

**Comment by karussell** [comment]
Seems it was a caching issue on my side. Sorry for the bubble and thx @boldtrn !

**Comment by boldtrn** [comment]
No worries, happy that I could help :)

**Pull request merged**
